---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-dev-pod.fullname" . }}
  labels:
    {{- include "k8s-dev-pod.labels" . | nindent 4 }}
spec:
  type: {{ .Values.headless.type }}
  clusterIP: None
  ports:
    - name: ssh
      port: 22
      targetPort: 3022
      protocol: TCP
  selector:
    matchLabels:
      {{- include "k8s-dev-pod.selectorLabels" . | nindent 6 }}
